version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - spring-boot-saml-api/target/spring-boot-saml-api-0.1-SNAPSHOT.jar
  discard-paths: yes